import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import MainLayout from '../modules/main/layout';

const Home: NextPage = () => {
  return (
    <div className="min-h-screen flex flex-col justify-center	items-center bg-cs-gray text-cs-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-cs-gray">
        <MainLayout />
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
